"""LLM client for natural language to SQL conversion using OpenAI."""

import logging
from typing import List, Optional

logger = logging.getLogger(__name__)


class LLMClient:
    """Client for OpenAI-based NL-to-SQL conversion."""
    
    def __init__(self, config):
        self.config = config
        self.client = None
        self._initialize_client()
    
    def _initialize_client(self):
        """Initialize OpenAI client."""
        if not self.config.llm.api_key:
            logger.warning("No OpenAI API key provided. Using mock mode.")
            return
        
        try:
            from openai import OpenAI
            
            self.client = OpenAI(api_key=self.config.llm.api_key)
            logger.info("OpenAI client initialized successfully")
            
        except ImportError:
            logger.error("OpenAI library not installed. Install with: pip install openai")
        except Exception as e:
            logger.error(f"Failed to initialize OpenAI client: {e}")
    
    def generate_sql(self, natural_language: str, schema_info: str = "") -> List[str]:
        """Generate SQL queries from natural language using OpenAI."""
        # Try OpenAI first (GPT-4 is accurate enough for all queries)
        if self.client:
            try:
                queries = self._generate_with_openai(natural_language, schema_info)
                
                if queries and len(queries) > 0:
                    # If we got less than required candidates, add more from OpenAI or mock
                    if len(queries) < self.config.optimizer.num_candidates:
                        logger.warning(f"Only got {len(queries)} valid queries from OpenAI")
                        # Try to get more from OpenAI
                        additional = self._generate_with_openai(natural_language, schema_info)
                        for q in additional:
                            if q not in queries:
                                queries.append(q)
                                if len(queries) >= self.config.optimizer.num_candidates:
                                    break
                        
                        # If still not enough, add mock ones
                        if len(queries) < self.config.optimizer.num_candidates:
                            mock_queries = self._mock_generate_sql(natural_language)
                            for mock_q in mock_queries:
                                if mock_q not in queries:
                                    queries.append(mock_q)
                                    if len(queries) >= self.config.optimizer.num_candidates:
                                        break
                    
                    return queries[:self.config.optimizer.num_candidates]
                else:
                    logger.warning("No valid SQL generated by OpenAI, using mock mode")
                    return self._mock_generate_sql(natural_language)
            
            except Exception as e:
                logger.error(f"OpenAI generation failed: {e}, falling back to mock mode")
                return self._mock_generate_sql(natural_language)
        else:
            # No OpenAI client available, use mock mode
            logger.warning("OpenAI not available, using mock mode")
            return self._mock_generate_sql(natural_language)
    
    def _generate_with_openai(self, nl_query: str, schema_info: str) -> List[str]:
        """Generate SQL using OpenAI."""
        prompt = f"""You are an expert SQL Server query generator.

Task: Convert this natural language query to valid SQL Server syntax.
Generate {self.config.optimizer.num_candidates} DIFFERENT valid SQL queries that achieve the same result.

Natural Language Query: "{nl_query}"

Database Schema:
{schema_info if schema_info else "Use INFORMATION_SCHEMA tables for metadata queries."}

Requirements:
1. Return ONLY valid, complete SQL queries
2. Each query must be syntactically correct and executable
3. Use different approaches (joins, subqueries, CTEs, etc.)
4. Each query on a separate line
5. End each query with semicolon
6. Do NOT include explanations or markdown

Example format:
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE';
SELECT name FROM sys.tables WHERE type = 'U';
SELECT SCHEMA_NAME(schema_id) + '.' + name FROM sys.tables WHERE type = 'U';
"""
        
        response = self.client.chat.completions.create(
            model=self.config.llm.model,
            messages=[
                {"role": "system", "content": "You are an expert SQL Server query generator. Generate only valid SQL queries without explanations."},
                {"role": "user", "content": prompt}
            ],
            temperature=self.config.llm.temperature,
            max_tokens=self.config.llm.max_tokens,
            n=self.config.optimizer.num_candidates
        )
        
        queries = []
        for choice in response.choices:
            sql = self._extract_sql(choice.message.content)
            if sql:
                queries.append(sql)
                logger.info(f"OpenAI generated SQL: {sql[:100]}...")
        
        return queries if queries else []
    
    def _extract_sql(self, text: str) -> Optional[str]:
        """Extract SQL from OpenAI response."""
        # Remove markdown code blocks
        text = text.strip()
        if text.startswith("```sql"):
            text = text[6:]
        if text.startswith("```"):
            text = text[3:]
        if text.endswith("```"):
            text = text[:-3]
        
        text = text.strip()
        
        # Add semicolon if missing
        if text and not text.endswith(';'):
            text = text + ';'
        
        # Check for incomplete WHERE clauses
        if 'WHERE' in text.upper() and not any(op in text for op in ['=', '>', '<', 'LIKE', 'IN', 'IS']):
            logger.warning(f"Skipping incomplete SQL: {text[:50]}...")
            return None
        
        # Check for unclosed quotes
        single_quotes = text.count("'")
        double_quotes = text.count('"')
        if single_quotes % 2 != 0 or double_quotes % 2 != 0:
            logger.warning(f"Skipping SQL with unclosed quotes: {text[:50]}...")
            return None
        
        # Check for basic SQL keywords
        if not any(keyword in text.upper() for keyword in ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'CREATE', 'DROP', 'ALTER']):
            logger.warning(f"Skipping non-SQL text: {text[:50]}...")
            return None
        
        return text if text else None
    
    def _mock_generate_sql(self, nl_query: str) -> List[str]:
        """Generate mock SQL queries for testing without LLM."""
        nl_lower = nl_query.lower()
        
        # Pattern matching for common queries
        # CHECK CREATE TABLE FIRST (before schema check)
        if "create" in nl_lower and "table" in nl_lower:
            # Extract table name
            words = nl_query.split()
            table_name = "NewTable"
            
            # Find table name - look for pattern "table called X", "table named X", or "table X"
            for i, word in enumerate(words):
                if word.lower() in ["called", "named"] and i + 1 < len(words):
                    # Pattern: "table called student" or "table named Orders"
                    potential_name = words[i + 1].strip("'\".,;")  # Remove quotes and punctuation
                    if potential_name.lower() not in ["with", "and", "having", "the", "a", "an"]:
                        table_name = potential_name
                        break
                elif word.lower() == "table" and i + 1 < len(words):
                    # Pattern: "create table student"
                    next_word = words[i + 1].strip("'\".,;")  # Remove quotes and punctuation
                    if next_word.lower() not in ["called", "named", "with", "and", "having", "the", "a", "an"]:
                        table_name = next_word
                        break
            
            # Extract column names and types from natural language
            columns = []
            
            # Look for "with X and Y columns" or "with X, Y columns" pattern
            if " with " in nl_lower:
                with_index = nl_lower.index(" with ")
                after_with = nl_query[with_index + 6:].strip()  # Get text after "with "
                
                # Remove "columns", "column", "attributes", "attribute", "fields", "field"
                after_with = after_with.replace(" columns", "").replace(" column", "")
                after_with = after_with.replace(" attributes", "").replace(" attribute", "")
                after_with = after_with.replace(" fields", "").replace(" field", "")
                
                # Split by "and" or ","
                col_names = []
                if " and " in after_with:
                    col_names = [c.strip() for c in after_with.split(" and ")]
                elif "," in after_with:
                    col_names = [c.strip() for c in after_with.split(",")]
                else:
                    col_names = [after_with.strip()]
                
                # Create columns with inferred types
                for col_name in col_names:
                    if col_name:
                        col_name = col_name.strip("'\".,;")
                        if col_name.lower() not in ["with", "and", "the", "a", "an", ""]:
                            # Determine type based on name
                            col_type = "VARCHAR(100)"
                            col_lower = col_name.lower()
                            
                            if "id" in col_lower:
                                col_type = "INT PRIMARY KEY" if col_name == col_names[0] else "INT"
                            elif "date" in col_lower or "time" in col_lower:
                                col_type = "DATETIME"
                            elif "price" in col_lower or "amount" in col_lower or "cost" in col_lower:
                                col_type = "DECIMAL(10,2)"
                            elif "age" in col_lower or "quantity" in col_lower or "count" in col_lower or "number" in col_lower:
                                col_type = "INT"
                            
                            columns.append(f"{col_name} {col_type}")
            
            # Look for explicit column mentions with "named" or "called"
            if not columns:
                for i, word in enumerate(words):
                    if word.lower() in ["column", "columns", "attribute", "attributes", "field", "fields"]:
                        # Look for column names after this keyword
                        if i + 1 < len(words):
                            potential_col = words[i + 1].strip("'\".,;")
                            if potential_col.lower() not in ["named", "called", "with", "and", "the", "a", "an"]:
                                # Determine type based on name
                                col_type = "VARCHAR(100)"
                                if "id" in potential_col.lower():
                                    col_type = "INT"
                                elif "date" in potential_col.lower() or "time" in potential_col.lower():
                                    col_type = "DATETIME"
                                elif "price" in potential_col.lower() or "amount" in potential_col.lower():
                                    col_type = "DECIMAL(10,2)"
                                elif "age" in potential_col.lower() or "quantity" in potential_col.lower():
                                    col_type = "INT"
                                
                                columns.append(f"{potential_col} {col_type}")
            
            # Common column patterns (fallback if no explicit columns found)
            if not columns:
                if "id" in nl_lower or "rollno" in nl_lower or "roll" in nl_lower or "productid" in nl_lower:
                    if "rollno" in nl_lower or "roll" in nl_lower:
                        columns.append("RollNo INT PRIMARY KEY")
                    elif "productid" in nl_lower:
                        columns.append("ProductId INT PRIMARY KEY")
                    else:
                        columns.append("ID INT PRIMARY KEY")
                
                if "name" in nl_lower:
                    columns.append("Name VARCHAR(100)")
                
                if "branch" in nl_lower:
                    columns.append("Branch VARCHAR(50)")
                
                if "age" in nl_lower:
                    columns.append("Age INT")
                
                if "email" in nl_lower:
                    columns.append("Email VARCHAR(100)")
                
                if "mobile" in nl_lower or "phone" in nl_lower:
                    columns.append("MobileNumber VARCHAR(20)")
                
                if "price" in nl_lower:
                    columns.append("Price DECIMAL(10,2)")
                
                if "stock" in nl_lower or "quantity" in nl_lower:
                    columns.append("Stock INT")
                
                if "address" in nl_lower:
                    columns.append("Address VARCHAR(255)")
                
                if "date" in nl_lower and "birth" not in nl_lower:
                    columns.append("Date DATETIME")
                
                if "description" in nl_lower or "desc" in nl_lower:
                    columns.append("Description VARCHAR(255)")
            
            # Default if no columns detected
            if not columns:
                columns = ["ID INT PRIMARY KEY", "Name VARCHAR(100)", "Description VARCHAR(255)"]
            
            col_str = ", ".join(columns)
            
            return [
                f"CREATE TABLE {table_name} ({col_str})",
                f"CREATE TABLE {table_name} ({columns[0]}, {', '.join(columns[1:])})" if len(columns) > 1 else f"CREATE TABLE {table_name} ({col_str})",
                f"CREATE TABLE dbo.{table_name} ({col_str})"
            ]
        
        elif "list" in nl_lower and "table" in nl_lower and "schema" not in nl_lower and "from" not in nl_lower and "of" not in nl_lower and "in" not in nl_lower:
            return [
                "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'",
                "SELECT name FROM sys.tables WHERE type = 'U'",
                "SELECT TABLE_SCHEMA + '.' + TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'"
            ]
        
        elif "schema" in nl_lower or "describe" in nl_lower or "structure" in nl_lower or (("column" in nl_lower or "columns" in nl_lower) and "add" not in nl_lower and "alter" not in nl_lower and "remove" not in nl_lower and "drop" not in nl_lower and "delete" not in nl_lower):
            # Try to extract table name
            table_name = "Customers"  # default
            words = nl_query.split()
            for i, word in enumerate(words):
                if word.lower() in ["of", "for", "from", "in"] and i + 1 < len(words):
                    potential_table = words[i + 1].strip('.,;')
                    if potential_table.lower() not in ["the", "a", "an", "database", "table"]:
                        # Capitalize first letter for common table names
                        if potential_table.lower() in ["customer", "customers"]:
                            table_name = "Customers"
                        else:
                            table_name = potential_table.capitalize()
                        break
            
            return [
                f"SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE LOWER(TABLE_NAME) = LOWER('{table_name}')",
                f"SELECT c.name AS ColumnName, t.name AS DataType, c.max_length, c.is_nullable FROM sys.columns c JOIN sys.types t ON c.user_type_id = t.user_type_id JOIN sys.tables tb ON c.object_id = tb.object_id WHERE LOWER(tb.name) = LOWER('{table_name}')",
                f"EXEC sp_columns '{table_name}'"
            ]
        
        elif "version" in nl_lower or ("server" in nl_lower and "sql" in nl_lower):
            return [
                "SELECT @@VERSION",
                "SELECT SERVERPROPERTY('ProductVersion') AS Version",
                "SELECT @@VERSION AS ServerVersion"
            ]
        
        elif "customer" in nl_lower and ("select" in nl_lower or "show" in nl_lower or "get" in nl_lower or "all" in nl_lower):
            return [
                "SELECT * FROM Customers",
                "SELECT CustomerID, Name, Age, MobileNumber FROM Customers ORDER BY CustomerID",
                "SELECT TOP 100 * FROM Customers"
            ]
        
        elif "customer" in nl_lower and "insert" in nl_lower:
            return [
                "INSERT INTO Customers (CustomerID, Name, Age, MobileNumber) VALUES (1, 'John Doe', 30, '1234567890')",
                "INSERT INTO Customers VALUES (1, 'John Doe', 30, '1234567890')",
                "INSERT INTO Customers (Name, Age, MobileNumber) VALUES ('John Doe', 30, '1234567890')"
            ]
        
        # Generic INSERT pattern
        elif "insert" in nl_lower:
            # Extract table name
            words = nl_query.split()
            table_name = None
            
            # Find table name - look for patterns like "into Text table" or "to Products"
            for i, word in enumerate(words):
                if word.lower() in ["into", "in", "to"] and i + 1 < len(words):
                    # Look ahead for table name
                    for j in range(i + 1, min(i + 4, len(words))):
                        potential_table = words[j].strip('.,;')
                        if potential_table.lower() not in ["the", "a", "an", "table", "some", "dummy", "data", "values"]:
                            table_name = potential_table
                            break
                    if table_name:
                        break
            
            # Default if not found
            if not table_name:
                table_name = "TableName"
            
            # Generate INSERT with dummy data
            return [
                f"INSERT INTO {table_name} (ID, Name, Description) VALUES (1, 'Sample Name', 'Sample Description')",
                f"INSERT INTO {table_name} VALUES (1, 'Sample Name', 'Sample Description')",
                f"INSERT INTO {table_name} (Name, Description) VALUES ('Sample Name', 'Sample Description')"
            ]
        
        # UPDATE pattern
        elif "update" in nl_lower and "set" in nl_lower:
            # Extract table name
            words = nl_query.split()
            table_name = None
            
            for i, word in enumerate(words):
                if word.lower() == "update" and i + 1 < len(words):
                    potential_table = words[i + 1].strip('.,;')
                    if potential_table.lower() not in ["the", "a", "an", "table", "set"]:
                        table_name = potential_table
                        break
            
            if not table_name:
                table_name = "TableName"
            
            return [
                f"UPDATE {table_name} SET Name = 'Updated Value' WHERE ID = 1",
                f"UPDATE {table_name} SET Name = 'Updated Value', Description = 'Updated Description' WHERE ID = 1",
                f"UPDATE {table_name} SET Name = 'Updated Value'"
            ]
        
        # DELETE rows pattern (not DROP TABLE or DROP COLUMN)
        elif ("delete" in nl_lower or "remove" in nl_lower) and "from" in nl_lower and "column" not in nl_lower and "table" not in nl_lower:
            # Extract table name
            words = nl_query.split()
            table_name = None
            
            for i, word in enumerate(words):
                if word.lower() == "from" and i + 1 < len(words):
                    potential_table = words[i + 1].strip('.,;')
                    if potential_table.lower() not in ["the", "a", "an", "table"]:
                        table_name = potential_table
                        break
            
            if not table_name:
                table_name = "TableName"
            
            return [
                f"DELETE FROM {table_name} WHERE ID = 1",
                f"DELETE FROM {table_name} WHERE Name = 'Sample'",
                f"DELETE FROM {table_name}"
            ]
        
        elif "drop" in nl_lower and "customer" in nl_lower:
            return [
                "DROP TABLE Customers",
                "DROP TABLE IF EXISTS Customers",
                "DROP TABLE dbo.Customers"
            ]
        
        # Generic CREATE TABLE pattern
        elif "create" in nl_lower and "table" in nl_lower:
            # Try to extract table name
            words = nl_query.split()
            table_name = "NewTable"
            for i, word in enumerate(words):
                if word.lower() in ["table", "called", "named"] and i + 1 < len(words):
                    table_name = words[i + 1].strip('.,;')
                    break
            
            return [
                f"CREATE TABLE {table_name} (id INT PRIMARY KEY, name VARCHAR(100), description VARCHAR(255))",
                f"CREATE TABLE {table_name} (id INT IDENTITY(1,1) PRIMARY KEY, name NVARCHAR(100), created_at DATETIME DEFAULT GETDATE())",
                f"CREATE TABLE dbo.{table_name} (id INT PRIMARY KEY, name VARCHAR(100))"
            ]
        
        # Generic SELECT pattern
        elif "select" in nl_lower or "show" in nl_lower or "list" in nl_lower:
            # Try to extract table name
            words = nl_query.split()
            table_name = None
            for i, word in enumerate(words):
                if word.lower() in ["from", "in"] and i + 1 < len(words):
                    table_name = words[i + 1].strip('.,;')
                    break
            
            if table_name:
                return [
                    f"SELECT * FROM {table_name}",
                    f"SELECT TOP 100 * FROM {table_name}",
                    f"SELECT * FROM {table_name} ORDER BY id"
                ]
        
        # DROP TABLE pattern (but not DROP COLUMN)
        elif ("drop" in nl_lower or "delete" in nl_lower or "remove" in nl_lower) and "table" in nl_lower and "column" not in nl_lower:
            # Extract table name (preserve original case)
            words = nl_query.split()
            table_name = "TableName"
            
            for i, word in enumerate(words):
                if word.lower() in ["table", "the"] and i + 1 < len(words):
                    potential_name = words[i + 1].strip("'\".,;")  # Remove quotes and punctuation
                    if potential_name.lower() not in ["from", "in", "table", "the", "a", "an", "my", "database", "called", "named"]:
                        # Preserve original case from user input
                        table_name = potential_name
                        break
                elif word.lower() in ["drop", "delete", "remove"] and i + 1 < len(words):
                    # Pattern: "drop Apps" or "delete Products"
                    next_word = words[i + 1].strip("'\".,;")
                    if next_word.lower() not in ["the", "a", "an", "table", "from", "in"]:
                        table_name = next_word
                        break
            
            return [
                f"DROP TABLE {table_name}",
                f"DROP TABLE IF EXISTS {table_name}",
                f"DROP TABLE dbo.{table_name}"
            ]
        
        # DROP COLUMN pattern (remove column from table)
        elif ("remove" in nl_lower or "drop" in nl_lower or "delete" in nl_lower) and "column" in nl_lower:
            # Extract table name and column name
            words = nl_query.split()
            table_name = None
            column_name = None
            
            # Find column name - look for patterns like "remove the word column" or "drop email column"
            for i, word in enumerate(words):
                if word.lower() in ["remove", "drop", "delete"] and i + 1 < len(words):
                    # Look ahead for column name (skip "the", "a", "an")
                    for j in range(i + 1, min(i + 4, len(words))):
                        potential_col = words[j].strip('.,;')
                        if potential_col.lower() not in ["the", "a", "an", "column", "from", "in"]:
                            column_name = potential_col
                            break
                    if column_name:
                        break
            
            # Find table name - look for patterns like "in Text table" or "from Users table"
            for i, word in enumerate(words):
                if word.lower() in ["in", "from"] and i + 1 < len(words):
                    # Look ahead for table name
                    for j in range(i + 1, min(i + 4, len(words))):
                        potential_table = words[j].strip('.,;')
                        if potential_table.lower() not in ["the", "a", "an", "table", "column"]:
                            table_name = potential_table
                            break
                    if table_name:
                        break
            
            # Defaults if not found
            if not column_name:
                column_name = "ColumnName"
            if not table_name:
                table_name = "TableName"
            
            return [
                f"ALTER TABLE {table_name} DROP COLUMN {column_name}",
                f"ALTER TABLE dbo.{table_name} DROP COLUMN {column_name}",
                f"ALTER TABLE {table_name} DROP COLUMN IF EXISTS {column_name}"
            ]
        
        # ALTER TABLE - ADD COLUMN pattern
        elif ("add" in nl_lower or "alter" in nl_lower) and ("column" in nl_lower or "table" in nl_lower or " to " in nl_lower):
            # Extract table name and column info
            words = nl_query.split()
            table_name = None
            column_name = None
            column_type = "VARCHAR(100)"  # default
            
            # Find table name - look for patterns like "to the Apps table" or "in Apps table" or "to Products"
            for i, word in enumerate(words):
                if word.lower() in ["in", "from"] and i + 1 < len(words):
                    # Look ahead for table name
                    for j in range(i + 1, min(i + 4, len(words))):
                        potential_table = words[j].strip('.,;')
                        if potential_table.lower() not in ["the", "a", "an", "column", "add", "table", "named", "called"]:
                            table_name = potential_table
                            break
                    if table_name:
                        break
                elif word.lower() == "to" and i + 1 < len(words):
                    # Pattern: "Add price to Products" or "Add email to the Users table"
                    # Look ahead past "the", "a", "an"
                    for j in range(i + 1, min(i + 4, len(words))):
                        next_word = words[j].strip('.,;')
                        if next_word.lower() not in ["the", "a", "an", "column"]:
                            # Check if it's "table" - if so, skip it
                            if next_word.lower() != "table":
                                table_name = next_word
                                break
                    if table_name:
                        break
            
            # Find column name - look for patterns like "column named Brand" or "add Brand column" or "add price"
            for i, word in enumerate(words):
                if word.lower() in ["named", "called"] and i + 1 < len(words):
                    potential_column = words[i + 1].strip('.,;')
                    if potential_column.lower() not in ["the", "a", "an", "to", "in", "column", "table"]:
                        column_name = potential_column
                        break
                elif word.lower() == "add" and i + 1 < len(words):
                    # Pattern: "add Brand to table" or "add price to Products"
                    potential_column = words[i + 1].strip('.,;')
                    if potential_column.lower() not in ["a", "an", "the", "column", "table", "to", "in"]:
                        column_name = potential_column
                        break
            
            # Detect column type from keywords or column name
            if column_name:
                col_lower = column_name.lower()
                if "email" in col_lower:
                    column_type = "VARCHAR(100)"
                elif "phone" in col_lower or "mobile" in col_lower or "number" in col_lower:
                    column_type = "VARCHAR(20)"
                elif "address" in col_lower:
                    column_type = "VARCHAR(255)"
                elif "age" in col_lower:
                    column_type = "INT"
                elif "date" in col_lower or "time" in col_lower:
                    column_type = "DATETIME"
                elif "price" in col_lower or "cost" in col_lower or "amount" in col_lower or "salary" in col_lower:
                    column_type = "DECIMAL(10,2)"
                elif "id" in col_lower:
                    column_type = "INT"
                elif "description" in col_lower or "comment" in col_lower or "note" in col_lower or "category" in col_lower:
                    column_type = "VARCHAR(255)"
                elif "name" in col_lower or "brand" in col_lower or "title" in col_lower:
                    column_type = "VARCHAR(100)"
                elif "quantity" in col_lower or "stock" in col_lower or "count" in col_lower:
                    column_type = "INT"
            
            # Fallback to generic detection if column name not found
            if not column_name:
                if "email" in nl_lower:
                    column_name = "Email"
                    column_type = "VARCHAR(100)"
                elif "phone" in nl_lower or "mobile" in nl_lower:
                    column_name = "PhoneNumber"
                    column_type = "VARCHAR(20)"
                elif "address" in nl_lower:
                    column_name = "Address"
                    column_type = "VARCHAR(255)"
                elif "age" in nl_lower:
                    column_name = "Age"
                    column_type = "INT"
                elif "date" in nl_lower:
                    column_name = "Date"
                    column_type = "DATETIME"
                elif "price" in nl_lower:
                    column_name = "Price"
                    column_type = "DECIMAL(10,2)"
                else:
                    column_name = "NewColumn"
            
            # Default table name if not found
            if not table_name:
                table_name = "Customers"
            
            return [
                f"ALTER TABLE {table_name} ADD {column_name} {column_type}",
                f"ALTER TABLE {table_name} ADD {column_name} {column_type} NULL",
                f"ALTER TABLE dbo.{table_name} ADD {column_name} {column_type} DEFAULT NULL"
            ]
        
        # Generic SELECT pattern
        elif "select" in nl_lower or ("show" in nl_lower and "column" not in nl_lower and "schema" not in nl_lower) or (("list" in nl_lower or "get" in nl_lower) and ("data" in nl_lower or "rows" in nl_lower or "records" in nl_lower or "all" in nl_lower)):
            # Try to extract table name
            words = nl_query.split()
            table_name = None
            
            for i, word in enumerate(words):
                if word.lower() in ["from", "in", "of"] and i + 1 < len(words):
                    potential_table = words[i + 1].strip('.,;')
                    if potential_table.lower() not in ["the", "a", "an", "table", "database"]:
                        table_name = potential_table
                        break
                elif word.lower() in ["show", "list", "get", "select"] and i + 1 < len(words):
                    # Pattern: "show Apps" or "list Products" or "get all data from Products"
                    # Look for table name after skipping common words
                    for j in range(i + 1, min(i + 5, len(words))):
                        next_word = words[j].strip('.,;')
                        if next_word.lower() not in ["all", "the", "a", "an", "from", "in", "of", "table", "data", "me", "records", "rows"]:
                            table_name = next_word
                            break
                    if table_name:
                        break
            
            if table_name:
                return [
                    f"SELECT * FROM {table_name}",
                    f"SELECT TOP 100 * FROM {table_name}",
                    f"SELECT * FROM {table_name} ORDER BY 1"
                ]
        
        # If no pattern matches, return default fallback
        return [
            "-- Could not parse query. Please provide valid SQL or use supported patterns.",
            "SELECT 'Unsupported query pattern' AS message",
            "SELECT 'Please try: List tables, Create table, Select from table, Add column' AS help"
        ]
