"""Test OpenAI integration."""
import requests
import json

print("="*70)
print("OPENAI INTEGRATION TEST")
print("="*70)

# Test query
response = requests.post(
    "http://localhost:8000/api/query/text",
    json={"query": "List all tables in my database"}
)

result = response.json()

print("\n✓ SQL Candidates Generated by OpenAI:")
for i, sql in enumerate(result['candidates'], 1):
    print(f"\n  {i}. {sql}")

print(f"\n✓ Selected SQL:")
print(f"  {result['selected_sql']}")

if result['result']:
    print(f"\n✓ Query Result:")
    print(f"  Tables found: {len(result['result']['rows'])}")
    for row in result['result']['rows']:
        print(f"    - {row[0]}")

print("\n" + "="*70)
if result['success']:
    print("✓ OpenAI integration working perfectly!")
else:
    print(f"✗ Error: {result.get('error')}")
print("="*70)
