"""Basic OpenAI integration test with 3 queries."""
import requests
import json
import time

def test_query(query_text, test_num):
    """Test a single query."""
    print(f"\n{'='*70}")
    print(f"TEST {test_num}: {query_text}")
    print('='*70)
    
    start = time.time()
    
    try:
        response = requests.post(
            "http://localhost:8000/api/query/text",
            json={"query": query_text},
            timeout=30
        )
        
        elapsed = time.time() - start
        
        if response.status_code == 200:
            result = response.json()
            
            print(f"\n✓ Response Time: {elapsed:.2f} seconds")
            print(f"✓ Success: {result['success']}")
            
            print(f"\n✓ SQL Candidates (Generated by OpenAI GPT-3.5-turbo):")
            for i, sql in enumerate(result['candidates'], 1):
                print(f"  {i}. {sql}")
            
            print(f"\n✓ Selected SQL:")
            print(f"  {result['selected_sql']}")
            
            if result['result'] and result['result']['rows']:
                print(f"\n✓ Result: {len(result['result']['rows'])} rows")
                for row in result['result']['rows'][:3]:
                    print(f"    {row}")
            
            return True
        else:
            print(f"\n✗ HTTP Error: {response.status_code}")
            return False
            
    except Exception as e:
        print(f"\n✗ Error: {e}")
        return False

if __name__ == "__main__":
    print("\n" + "="*70)
    print("OPENAI GPT-3.5-TURBO INTEGRATION TEST")
    print("="*70)
    print("Model: gpt-3.5-turbo")
    print("Testing 3 different query types...")
    
    results = []
    
    # Test 1: List tables
    results.append(test_query("List all tables in my database", 1))
    
    # Test 2: Create table
    results.append(test_query("Create a table called Products with id, name, and price columns", 2))
    
    # Test 3: Schema query
    results.append(test_query("Show me the columns in the Customers table", 3))
    
    # Summary
    print("\n" + "="*70)
    print("TEST SUMMARY")
    print("="*70)
    passed = sum(results)
    print(f"Passed: {passed}/3")
    print(f"Failed: {3-passed}/3")
    
    if passed == 3:
        print("\n✓ All tests passed! OpenAI integration working perfectly!")
    else:
        print(f"\n⚠ {3-passed} test(s) failed")
    
    print("="*70 + "\n")
