"""Test SQLCoder-7B-2 via Transformers integration."""

import requests
import json
import time

BASE_URL = "http://localhost:8000"

def test_health():
    """Test if server is running."""
    try:
        response = requests.get(f"{BASE_URL}/health", timeout=5)
        if response.status_code == 200:
            print("✓ Server is running")
            return True
    except:
        print("✗ Server is not running")
        return False

def test_query(query_text):
    """Test a natural language query."""
    print(f"\n{'='*70}")
    print(f"Query: {query_text}")
    print('='*70)
    
    start_time = time.time()
    
    try:
        response = requests.post(
            f"{BASE_URL}/api/query/text",
            json={"query": query_text},
            headers={"Content-Type": "application/json"},
            timeout=120  # 2 minutes for CPU inference
        )
        
        elapsed = time.time() - start_time
        
        if response.status_code == 200:
            result = response.json()
            print(f"\n✓ Success: {result['success']}")
            print(f"✓ Time: {elapsed:.1f} seconds")
            
            print(f"\n✓ SQL Candidates Generated:")
            for i, sql in enumerate(result['candidates'], 1):
                print(f"\n  {i}. {sql}")
            
            print(f"\n✓ Selected SQL:")
            print(f"  {result['selected_sql']}")
            
            if result['result']:
                print(f"\n✓ Query Result:")
                print(f"  Columns: {result['result']['columns']}")
                print(f"  Rows: {len(result['result']['rows'])}")
                if result['result']['rows']:
                    for row in result['result']['rows'][:5]:
                        print(f"    {row}")
            
            if result.get('error'):
                print(f"\n✗ Error: {result['error']}")
        else:
            print(f"\n✗ HTTP {response.status_code}: {response.text}")
    
    except requests.Timeout:
        print(f"\n✗ Request timed out after {time.time() - start_time:.1f} seconds")
        print("  (This is normal on first run - model is downloading)")
    except Exception as e:
        print(f"\n✗ Error: {e}")

if __name__ == "__main__":
    print("\n" + "="*70)
    print("SQLCODER-7B-2 TRANSFORMERS INTEGRATION TEST")
    print("="*70)
    print("\nModel: defog/sqlcoder-7b-2")
    print("Device: CPU (no CUDA detected)")
    print("\nNOTE: First run will download ~14 GB model")
    print("      CPU inference takes 30-60 seconds per query")
    
    # Check server
    if not test_health():
        print("\n✗ Please start the server first: python run_api.py")
        exit(1)
    
    # Test 1: Simple query
    test_query("List all tables in my database")
    
    # Test 2: Schema query
    test_query("Show me the columns in the Customers table")
    
    print("\n" + "="*70)
    print("TEST COMPLETE!")
    print("="*70)
    print("\nIf you see SQL generated by SQLCoder (not mock mode),")
    print("the integration is working correctly!")
    print("="*70 + "\n")
